/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "fulladder.v:1" *)
module full_adder_behavioural(a, b, carry_in, sum_output, carry_out);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "fulladder.v:2" *)
  input a;
  (* src = "fulladder.v:3" *)
  input b;
  (* src = "fulladder.v:4" *)
  input carry_in;
  (* src = "fulladder.v:6" *)
  output carry_out;
  (* src = "fulladder.v:5" *)
  output sum_output;
  assign _0_ = ~carry_in;
  assign _1_ = ~(b & a);
  assign _2_ = ~(b ^ a);
  assign carry_out = ~((_2_ | _0_) & _1_);
  assign sum_output = _2_ ^ _0_;
endmodule
